linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - hugeParam
      - rangeValCopy

linters:
  disable-all: true
  enable:
    - bodyclose
    - exportloopref
    - gas
    - gochecknoinits
    - gocritic
    - gosimple
    - govet
    - ineffassign
    - megacheck
    - misspell
    - nakedret
    - prealloc
    - revive
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused

  fast: false

run:
  concurrency: 4
