linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - hugeParam
      - rangeValCopy

linters:
  disable-all: true
  enable:
    - bodyclose
    - exportloopref
    - gas
    - gochecknoinits
    - gocritic
    - gosimple
    - govet
    - ineffassign
    - megacheck
    - misspell
    - nakedret
    - prealloc
    - revive
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused

  fast: false

run:
  concurrency: 4
