# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TelegramBanhammer < Formula
  desc "A program which uses MTProto Telegram API to ban spammers from a group."
  homepage "https://github.com/paskal/telegram-banhammer"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/paskal/telegram-banhammer/releases/download/v0.3.2/telegram-banhammer_0.3.2_macos_x86_64.tar.gz"
      sha256 "b633a03994225573f66968acf7e421484b4ad4fb2633b35623883bc19d49d554"

      def install
        bin.install "telegram-banhammer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/paskal/telegram-banhammer/releases/download/v0.3.2/telegram-banhammer_0.3.2_macos_arm64.tar.gz"
      sha256 "bdf0d073e9e8e888fda4ec5978cac9f8b34a0fea646050cd5617e5ce89b2feae"

      def install
        bin.install "telegram-banhammer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/paskal/telegram-banhammer/releases/download/v0.3.2/telegram-banhammer_0.3.2_linux_armv6.tar.gz"
      sha256 "072296140a92902cb975003e5e457506b05d05ff2aff4e9c92955faa3f23036d"

      def install
        bin.install "telegram-banhammer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/paskal/telegram-banhammer/releases/download/v0.3.2/telegram-banhammer_0.3.2_linux_arm64.tar.gz"
      sha256 "5a5de4849159ea213f916dfe2018fcad4dd8acf79228a032a6b005c27dfcf983"

      def install
        bin.install "telegram-banhammer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/paskal/telegram-banhammer/releases/download/v0.3.2/telegram-banhammer_0.3.2_linux_x86_64.tar.gz"
      sha256 "e53c7093169bbd45c5a994fb7e5cf2d6f1f6ff7e0fdb90f5db84b584aad9876b"

      def install
        bin.install "telegram-banhammer"
      end
    end
  end

  test do
    system "#{bin}/telegram-banhammer --help"
  end
end
