# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TelegramBanhammer < Formula
  desc "A program which uses MTProto Telegram API to ban spammers from a group."
  homepage "https://github.com/paskal/telegram-banhammer"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/paskal/telegram-banhammer/releases/download/v1.0.1/telegram-banhammer_1.0.1_macos_arm64.tar.gz"
      sha256 "300243186d411cd7f4ab664a3e0cacbff22717cfda3b53a0f5a49a7ecd3ba9bc"

      def install
        bin.install "telegram-banhammer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/paskal/telegram-banhammer/releases/download/v1.0.1/telegram-banhammer_1.0.1_macos_x86_64.tar.gz"
      sha256 "1bf5e6e19a912bd99cd04654bd0ddc4f22c2107c11d8b1118ef62227374241fd"

      def install
        bin.install "telegram-banhammer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/paskal/telegram-banhammer/releases/download/v1.0.1/telegram-banhammer_1.0.1_linux_arm64.tar.gz"
      sha256 "30360e78a3505b94dc6659b2552678149d25cb6bc6e4e7caaeed258d9241f91f"

      def install
        bin.install "telegram-banhammer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/paskal/telegram-banhammer/releases/download/v1.0.1/telegram-banhammer_1.0.1_linux_x86_64.tar.gz"
      sha256 "f49441dc36b351faab442fa544400c33ff95338fd36c22e4fa7a4aa526c0eec4"

      def install
        bin.install "telegram-banhammer"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/paskal/telegram-banhammer/releases/download/v1.0.1/telegram-banhammer_1.0.1_linux_armv6.tar.gz"
      sha256 "76e57406b2e56e4e1aead66cf54359133b34858fc1ca5e08fdcf19f0b3d3affc"

      def install
        bin.install "telegram-banhammer"
      end
    end
  end

  test do
    system "#{bin}/telegram-banhammer --help"
  end
end
